jaco_arm_controller:
  # type: "position_controllers/JointTrajectoryController"
  # jaco_joint_1:
  # type: velocity_controllers/JointTrajectoryController
  #   joint: jaco_joint_1 GroupVelocity
  #   pid: {p: 400.0, d: 5500.0, i: 1800.0, i_clamp: 2.0}
  type: "velocity_controllers/JointGroupVelocityController"
  publish_rate: 100
  
  joints:
    - jaco_joint_1
    - jaco_joint_2
    - jaco_joint_3
    - jaco_joint_4
    - jaco_joint_5
    - jaco_joint_6

  constraints:
    goal_time: 60
    jaco_joint_1:
      goal: 0.1
    jaco_joint_2:
      goal: 0.1
    jaco_joint_3:
      goal: 0.1
    jaco_joint_4:
      goal: 0.1
    jaco_joint_5:
      goal: 0.1
    jaco_joint_6:
      goal: 0.1
    stopped_velocity_tolerance: 0.1

  gains:
    jaco_joint_1:
      {p: 1.0, d: 0.0, i: 0.0, i_clamp: 0.0}
    jaco_joint_2:
      {p: 1.0, d: 0.0, i: 0.0, i_clamp: 0.0}
    jaco_joint_3:
      pid: {p: 400.0, d: 5500.0, i: 1800.0, i_clamp: 2.0}
    jaco_joint_4:
      pid: {p: 400.0, d: 5500.0, i: 1800.0, i_clamp: 2.0}
    jaco_joint_5:
      {p: 1.0, d: 0.0, i: 0.0, i_clamp: 0.0}
    jaco_joint_6:
      {p: 1.0, d: 0.0, i: 0.0, i_clamp: 0.0}

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
